# Generated by Django 5.2.7 on 2025-10-10 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_used', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('repollas', models.IntegerField(default=0)),
                ('boxes', models.IntegerField(default=0)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_used', models.ManyToManyField(related_name='productions', to='item_used.itemused')),
            ],
        ),
    ]
