# Generated by Django 5.2.7 on 2025-10-10 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('measurament', models.CharField(choices=[('ml', 'Mililiter'), ('u', 'Unit'), ('gm', 'Gram')], default='gm', max_length=10)),
            ],
        ),
    ]
