# Generated by Django 5.2.7 on 2025-10-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_used', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemused',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
