# Generated by Django 5.2.7 on 2025-10-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
